"""Deterministic SVG figures with data-tip attributes for the site and paper.

path_strips()      Figure 2: the ordered path of each regime (structure, not calendar)
response_plot()    Figure 3: trigger-to-rule lag against instrument strength
mechanism_matrix() Figure 4: who pays, selects, sees, publishes, oversees (now)
"""
from __future__ import annotations
import pathlib
from .paths import paths, analogues, responses, mechanisms, LETTER_LABEL

FONT = 'font-family="Instrument Sans, system-ui, sans-serif"'
INK, MUTED, PAPER, RULE = "#15222E", "#5E6B76", "#F4F6F3", "#D3DAD6"
COL = {"V": "#DCEFEA", "T": "#15222E", "M": "#0F766E", "S": "#8CC5BB", "O": "#2B4C7E", "I": "#6C4AB6", "A": "#3E8E7E", "D": "#B7791F", "P": "#B7791F", "R": "#9B2C2C"}
TXT = {"V": INK, "T": "#fff", "M": "#fff", "S": INK, "O": "#fff", "I": "#fff", "A": "#fff", "D": "#fff", "P": "#fff", "R": "#fff"}

def _esc(s: str) -> str:
    return str(s).replace("&", "&amp;").replace("<", "&lt;").replace('"', "&quot;")

def path_strips() -> str:
    ps = paths(); dist = {a["id"]: a for a in analogues()}
    rh, cell, name_w, pad = 30, 24, 250, 12
    w = name_w + cell * 14 + 300; h = 90 + rh * len(ps) + 40
    o = [f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {w} {h}" width="{w}" height="{h}" {FONT} font-size="12">',
         f'<rect width="{w}" height="{h}" fill="{PAPER}"/>',
         f'<text x="{pad}" y="22" font-size="16" fill="{INK}">Paths: the order each regime did things, ignoring the calendar</text>',
         f'<text x="{pad}" y="40" fill="{MUTED}">Consecutive repeats collapsed. Right column: similarity of each regime\'s opening to frontier AI\'s path so far (1 = identical, 0 = nothing shared).</text>']
    x0 = pad; y = 60
    for n_, (k, lab) in enumerate(LETTER_LABEL.items()):
        if n_ == 6: x0 = pad; y += 18
        o.append(f'<rect x="{x0}" y="{y - 11}" width="14" height="14" rx="2" fill="{COL[k]}"/><text x="{x0 + 18}" y="{y}" fill="{MUTED}">{lab}</text>')
        x0 += 30 + len(lab) * 6.6
    y = 104
    for p in ps:
        ai = p["id"] == "frontier-ai"
        if ai: o.append(f'<rect x="{pad - 4}" y="{y - 2}" width="{w - 2 * pad + 8}" height="{rh}" fill="#EAF4F1" rx="3"/>')
        o.append(f'<text x="{pad}" y="{y + 16}" fill="{INK}" font-weight="{"600" if ai else "400"}">{_esc(p["name"][:38])}</text>')
        # one glyph per collapsed step; tooltip lists every milestone in that run
        runs = []
        for s in p["steps"]:
            if runs and runs[-1][0] == s["letter"]: runs[-1][1].append(s)
            else: runs.append([s["letter"], [s]])
        for j, (letter, steps) in enumerate(runs):
            x = pad + name_w + j * cell
            tip = f"{p['name']}: {LETTER_LABEL[letter]}. " + " | ".join(f"{s['year']} {s['event']}" for s in steps)
            o.append(f'<g data-tip="{_esc(tip)}" style="cursor:pointer"><rect x="{x}" y="{y + 3}" width="{cell - 4}" height="{cell - 4}" rx="3" fill="{COL[letter]}"/>'
                     f'<text x="{x + (cell - 4) / 2}" y="{y + 17}" text-anchor="middle" fill="{TXT[letter]}" font-weight="600">{letter}</text>'
                     f'<text x="{x + (cell - 4) / 2}" y="{y + 27}" text-anchor="middle" fill="{MUTED}" font-size="8">{steps[0]["year"]}</text></g>')
        if not ai:
            d = dist[p["id"]]; xr = pad + name_w + 14 * cell + 10
            o.append(f'<rect x="{xr}" y="{y + 7}" width="{max(2, (1 - d["distance"]) * 120)}" height="12" fill="#0F766E" opacity="0.7"/>'
                     f'<text x="{xr + max(2, (1 - d["distance"]) * 120) + 5}" y="{y + 17}" fill="{MUTED}">similarity {1 - d["distance"]:.2f}, opening {d["matched_opening"]}</text>')
        else:
            o.append(f'<text x="{pad + name_w + 14 * cell + 10}" y="{y + 17}" fill="{MUTED}">reference path: {p["letters"]}</text>')
        y += rh
    o.append(f'<text x="{pad}" y="{h - 12}" fill="{MUTED}">Source: data/industries/. Generated by bench.figures.</text></svg>')
    return "\n".join(o)

def response_plot() -> str:
    rs = responses(); w, h = 760, 380; pl, pr, pt, pb = 60, 20, 60, 50
    xmax = 20; pw, ph = w - pl - pr, h - pt - pb
    o = [f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {w} {h}" width="{w}" height="{h}" {FONT} font-size="12">',
         f'<rect width="{w}" height="{h}" fill="{PAPER}"/>',
         f'<text x="{pl}" y="22" font-size="16" fill="{INK}">After a failure: how fast the next rule came, and how strong it was</text>',
         f'<text x="{pl}" y="40" fill="{MUTED}">Each point is one trigger incident. Hollow points: no rule followed. Frontier AI in teal.</text>']
    for s in range(1, 5):
        yy = pt + ph - (s - 1) / 3 * ph
        o.append(f'<line x1="{pl}" x2="{w - pr}" y1="{yy}" y2="{yy}" stroke="{RULE}"/><text x="{pl - 8}" y="{yy + 4}" text-anchor="end" fill="{MUTED}">{s}</text>')
    for lag in range(0, xmax + 1, 5):
        xx = pl + lag / xmax * pw
        o.append(f'<text x="{xx}" y="{h - pb + 18}" text-anchor="middle" fill="{MUTED}">{lag}</text>')
    o.append(f'<text x="{pl + pw / 2}" y="{h - 12}" text-anchor="middle" fill="{INK}">years from trigger to next rule</text>')
    o.append(f'<text transform="translate(16,{pt + ph / 2}) rotate(-90)" text-anchor="middle" fill="{INK}">instrument strength (1 disclosure to 4 structural)</text>')
    # deterministic jitter by index
    for i, r in enumerate(rs):
        ai = r["regime"] == "frontier-ai"
        if r["lag"] is None:
            xx = pl + pw + 6; yy = pt + ph + 4 - (i % 5) * 6
            tip = f"{r['name']}, {r['year']}: {r['trigger']}. No rule of any kind followed in the dataset."
            o.append(f'<circle data-tip="{_esc(tip)}" cx="{xx}" cy="{yy}" r="6" fill="none" stroke="{"#0F766E" if ai else INK}" stroke-width="1.5" style="cursor:pointer"/>')
            continue
        jit = ((i * 7) % 11 - 5) * 2.2
        xx = pl + min(r["lag"], xmax) / xmax * pw + ((i * 3) % 5 - 2) * 2.4
        yy = pt + ph - (r["strength"] - 1) / 3 * ph + jit
        tip = f"{r['name']}, {r['year']}: {r['trigger']} ({r['harm']}). Response after {r['lag']} year(s), strength {r['strength']}: {r['response_year']} {r['response']}"
        o.append(f'<circle data-tip="{_esc(tip)}" cx="{xx:.1f}" cy="{yy:.1f}" r="{7 if ai else 6}" fill="{"#0F766E" if ai else INK}" fill-opacity="{0.9 if ai else 0.55}" style="cursor:pointer"/>')
    o.append(f'<text x="{pl + pw + 6}" y="{pt + ph + 22}" text-anchor="middle" fill="{MUTED}" font-size="10">none</text>')
    o.append('</svg>')
    return "\n".join(o)

def mechanism_matrix() -> str:
    ms = mechanisms(); cols = [("pays", "Who pays"), ("selects", "Who selects"), ("access", "What they see"), ("publishes", "What the public reads"), ("oversees", "Who watches assessors")]
    val_col = {"A": ("#9B2C2C", "assessed party"), "R": ("#2B4C7E", "regulator or state"), "O": ("#0F766E", "opposing exposure"), "Ph": ("#6C4AB6", "philanthropy"), "self": ("#5E6B76", "self-organized"),
               "shallow": ("#9B2C2C", "shallow"), "deep": ("#8CC5BB", "deep"), "embedded": ("#0F766E", "embedded"),
               "none": ("#9B2C2C", "none"), "summary": ("#8CC5BB", "summary or mark"), "public": ("#0F766E", "public"),
               "self-reg": ("#B7791F", "industry self-regulation"), "regulator": ("#0F766E", "regulator")}
    rh, cw, name_w, pad = 26, 168, 250, 12
    w = pad + name_w + cw * len(cols) + 20; h = 80 + rh * len(ms) + 30
    o = [f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {w} {h}" width="{w}" height="{h}" {FONT} font-size="12">',
         f'<rect width="{w}" height="{h}" fill="{PAPER}"/>',
         f'<text x="{pad}" y="22" font-size="16" fill="{INK}">Mechanisms today: the incentive configuration of each regime</text>',
         f'<text x="{pad}" y="40" fill="{MUTED}">Red marks the configuration that concentrates control in the assessed party. Hover a cell for the state before reform.</text>']
    for j, (_, lab) in enumerate(cols):
        o.append(f'<text x="{pad + name_w + j * cw + cw / 2}" y="66" text-anchor="middle" fill="{INK}" font-weight="600">{lab}</text>')
    ai_now = next(m["now"] for m in ms if m["id"] == "frontier-ai")
    y = 78
    for m in ms:
        ai = m["id"] == "frontier-ai"; same = (m["now"] == ai_now and not ai)
        if ai: o.append(f'<rect x="{pad - 4}" y="{y - 2}" width="{w - 2 * pad + 8}" height="{rh}" fill="#EAF4F1" rx="3"/>')
        o.append(f'<text x="{pad}" y="{y + 16}" fill="{INK}" font-weight="{"600" if ai else "400"}">{_esc(m["name"][:36])}{" (same as AI)" if same else ""}</text>')
        for j, (key, lab) in enumerate(cols):
            v = m["now"][key]; b = m["before"][key]; col, label = val_col[v]
            tip = f"{m['name']}, {lab.lower()}: {label} now; before reform: {val_col[b][1]}. {m['note']}"
            x = pad + name_w + j * cw
            o.append(f'<g data-tip="{_esc(tip)}" style="cursor:pointer"><rect x="{x + 2}" y="{y + 2}" width="{cw - 4}" height="{rh - 6}" rx="2" fill="{col}" fill-opacity="{0.9 if col != "#8CC5BB" else 1}"/>'
                     f'<text x="{x + cw / 2}" y="{y + 16}" text-anchor="middle" fill="{"#fff" if col not in ("#8CC5BB",) else INK}">{label}{"" if v == b else " *"}</text></g>')
        y += rh
    o.append(f'<text x="{pad}" y="{h - 12}" fill="{MUTED}">* changed since the regime\'s origin. Source: data/industries/ mechanisms. Generated by bench.figures.</text></svg>')
    return "\n".join(o)

def write(dist: pathlib.Path, figs: pathlib.Path) -> None:
    for name, fn in [("paths", path_strips), ("responses", response_plot), ("mechanisms", mechanism_matrix), ("exposure", exposure_matrix), ("graph", funding_graph)]:
        s = fn(); (dist / f"{name}.svg").write_text(s); (figs / f"{name}.svg").write_text(s)

def exposure_matrix() -> str:
    """Figure 5: per-evaluator inflows by hop distance, ties within two hops, confirmed share."""
    from .ledger import load_ledger, exposure
    L = load_ledger(); ex = exposure(L)  # every evaluator, so an empty row is visible as a gap
    order = ["hop0", "hop1", "hop2", "hop3", "public", "unattributed"]
    labels = {"hop0": "Lab (0)", "hop1": "Lab-tied (1)", "hop2": "Two steps (2)", "hop3": "Three steps (3)", "public": "Public budget", "unattributed": "Donor not public"}
    shade = {"hop0": "#9B2C2C", "hop1": "#C4746A", "hop2": "#B7791F", "hop3": "#8CC5BB", "public": "#0F766E", "unattributed": "#5E6B76"}
    rh, cw, name_w, pad = 26, 116, 250, 12
    w = pad + name_w + cw * len(order) + 340; h = 96 + rh * len(ex) + 30
    o = [f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {w} {h}" width="{w}" height="{h}" {FONT} font-size="12">',
         f'<rect width="{w}" height="{h}" fill="{PAPER}"/>',
         f'<text x="{pad}" y="22" font-size="16" fill="{INK}">Traced money by distance from a frontier lab, per evaluator</text>',
         f'<text x="{pad}" y="40" fill="{MUTED}">Cell: number of inflow rows at that distance; the amount below is summed within the largest measure at that distance. Undisclosed amounts count as rows only.</text>',
         f'<text x="{pad}" y="56" fill="{MUTED}">Right: board, advisor, donor, investor, or office ties within two steps of a lab, and the share of rows re-derived from sources (confirmed) rather than imported.</text>']
    for j, k in enumerate(order):
        o.append(f'<text x="{pad + name_w + j * cw + cw / 2}" y="84" text-anchor="middle" fill="{INK}" font-weight="600">{labels[k]}</text>')
    xr = pad + name_w + len(order) * cw + 10
    o.append(f'<text x="{xr}" y="84" fill="{INK}" font-weight="600">Ties</text><text x="{xr + 60}" y="84" fill="{INK}" font-weight="600">Confirmed</text><text x="{xr + 140}" y="84" fill="{INK}" font-weight="600">Negatives</text><text x="{xr + 215}" y="84" fill="{INK}" font-weight="600">2nd hop</text>')
    y = 96
    for x in ex:
        o.append(f'<text x="{pad}" y="{y + 16}" fill="{INK}">{_esc(x["name"][:36])}</text>')
        if not x["inflow_rows"] and not x["lab_tied_seats"] and not x["negatives"]:
            o.append(f'<text x="{pad + name_w + 8}" y="{y + 16}" fill="{MUTED}" font-style="italic">no ledger rows yet; funding and ties not traced</text>')
            y += rh; continue
        for j, k in enumerate(order):
            b = x["buckets"].get(k); cx = pad + name_w + j * cw
            if not b:
                o.append(f'<rect x="{cx + 2}" y="{y + 2}" width="{cw - 4}" height="{rh - 6}" fill="none" stroke="{RULE}" stroke-dasharray="3 3"/>'); continue
            amt = ""
            if b["by_measure"]:
                m, v = max(b["by_measure"].items(), key=lambda kv: kv[1]); amt = f"{m} ${v/1e6:.1f}M" if v < 1e9 else f"{m} ${v/1e9:.1f}B"
            tip = f"{x['name']}, {labels[k].lower()}: {b['rows']} row(s) from {', '.join(b['sources'])}. " + (", ".join(f"{m} ${v/1e6:.1f}M" for m, v in b["by_measure"].items()) if b["by_measure"] else "amounts undisclosed") + (f"; {b['undisclosed']} undisclosed" if b["undisclosed"] and b["by_measure"] else "")
            op = 0.35 + 0.15 * min(b["rows"], 4)
            o.append(f'<g data-tip="{_esc(tip)}" style="cursor:pointer"><rect x="{cx + 2}" y="{y + 2}" width="{cw - 4}" height="{rh - 6}" rx="2" fill="{shade[k]}" fill-opacity="{op:.2f}"/>'
                     f'<text x="{cx + cw / 2}" y="{y + 12}" text-anchor="middle" fill="{INK}" font-weight="600" font-size="11">{b["rows"]}{"*" if b["undisclosed"] else ""}</text>'
                     f'<text x="{cx + cw / 2}" y="{y + 21}" text-anchor="middle" fill="{INK}" font-size="8.5">{_esc(amt)}</text></g>')
        ties = x["lab_tied_seats"]; conf = f"{x['confirmed_rows']}/{x['inflow_rows']}" if x["inflow_rows"] else "0/0"
        tie_tip = "; ".join(f"{t['via']} ({t['role']}, distance {t['distance']}, {t['status']})" for t in ties) or "no ties within two steps recorded"
        neg_tip = "; ".join(f"{n['claim']} [{n['searched']}, {n['snapshot']}, {n['status']}]" for n in x["negatives"]) or "no bounded negatives on file"
        o.append(f'<g data-tip="{_esc(x["name"] + ": " + tie_tip)}" style="cursor:pointer"><text x="{xr + 12}" y="{y + 16}" fill="{"#9B2C2C" if ties else MUTED}" font-weight="{"600" if ties else "400"}">{len(ties)}</text></g>')
        o.append(f'<text x="{xr + 70}" y="{y + 16}" fill="{MUTED}">{conf}</text>')
        o.append(f'<g data-tip="{_esc(x["name"] + ": " + neg_tip)}" style="cursor:pointer"><text x="{xr + 155}" y="{y + 16}" fill="{"#0F766E" if x["negatives"] else MUTED}">{len(x["negatives"])}</text></g>')
        sh = x["second_hop"]; sh_tip = f"{x['name']}: the ledger says something about who is behind {sh['traced']} of {sh['sources']} funding sources." + (" Untraced: " + ", ".join(sh["untraced"]) + "." if sh["untraced"] else "")
        o.append(f'<g data-tip="{_esc(sh_tip)}" style="cursor:pointer"><text x="{xr + 225}" y="{y + 16}" fill="{MUTED if sh["traced"] == sh["sources"] else "#B7791F"}">{sh["traced"]}/{sh["sources"]}</text></g>')
        y += rh
    o.append(f'<text x="{pad}" y="{h - 12}" fill="{MUTED}">* includes undisclosed amounts. Source: data/ledger/. Generated by bench.figures. Imported rows are leads until confirmed.</text></svg>')
    return "\n".join(o)


def funding_graph(focus: str | None = None, L: dict | None = None) -> str:
    """Figure 6: entities placed by distance from a lab, with money and role edges.

    With ``focus`` set, the focused node, its one-hop neighbours and their edges
    are drawn at full opacity and everything else is faded, which is the state
    the hover interaction produces on the site. Nodes carry data-node and edges
    carry data-from and data-to so a few lines of script can do the same live.
    """
    from .ledger import load_ledger, distances
    L = L or load_ledger(); E = L["entities"]; d = distances(L)
    neigh = set()
    if focus:
        neigh.add(focus)
        for t in L["transfers"]:
            if t["from"] == focus: neigh.add(t["to"])
            if t["to"] == focus: neigh.add(t["from"])
        for r in L["relationships"]:
            if r["subject"] == focus: neigh.add(r["object"])
            if r["object"] == focus: neigh.add(r["subject"])
    def nfade(e): return "" if (not focus or e in neigh) else ' opacity="0.12"'
    def efade(a, b): return "" if (not focus or a == focus or b == focus) else ' opacity="0.08"'
    def col(e):
        k = E[e]["kind"]
        if k == "evaluator": return 5
        if k == "public": return 4
        dd = d.get(e); return 4 if dd is None else min(int(dd), 3)
    used = set()
    for t in L["transfers"]: used.add(t["from"]); used.add(t["to"])
    for r in L["relationships"]: used.add(r["subject"]); used.add(r["object"])
    cols = {c: [] for c in range(6)}
    for e in sorted(used, key=lambda e: (E[e]["kind"] != "lab", E[e]["name"].lower())): cols[col(e)].append(e)
    labels = {0: "Labs", 1: "Direct lab ties", 2: "Two steps", 3: "Three or more", 4: "Public or unattributed", 5: "Evaluators"}
    cw, pad, top, rh = 210, 12, 70, 19
    h = top + rh * max(len(v) for v in cols.values()) + 40; w = pad * 2 + cw * 6
    pos = {}
    title = f"The funding graph around {E[focus]['name']}" if focus else "The funding graph, laid out by distance from a lab"
    o = [f'<svg xmlns="http://www.w3.org/2000/svg" class="fundgraph" viewBox="0 0 {w} {h}" width="{w}" height="{h}" {FONT} font-size="11">',
         f'<rect width="{w}" height="{h}" fill="{PAPER}"/>',
         f'<text x="{pad}" y="22" font-size="16" fill="{INK}">{_esc(title)}</text>',
         f'<text x="{pad}" y="40" fill="{MUTED}">Teal lines are money (transfers); amber lines are roles. Solid: confirmed; dashed: imported. Hover a name to isolate it and its neighbours; hover a line for the row. Every element is a row in data/ledger/.</text>']
    for c, names in cols.items():
        x = pad + c * cw
        o.append(f'<text x="{x}" y="{top - 12}" fill="{INK}" font-weight="600">{labels[c]}</text>')
        for i, e in enumerate(names):
            y = top + i * rh; pos[e] = (x, y)
    def nm(e): return E[e]["name"][:30]
    for t in L["transfers"]:
        if t["from"] in pos and t["to"] in pos:
            (x1, y1), (x2, y2) = pos[t["from"]], pos[t["to"]]; x1 += min(len(nm(t["from"])) * 6, cw - 20); mx = (x1 + x2) / 2
            tip = f"{t['row_id']} {E[t['from']]['name']} to {E[t['to']]['name']}: {t['measure']}" + (f" ${float(t['amount_usd'])/1e6:.1f}M" if t["amount_usd"] else " (amount undisclosed)") + f", {t['date']}. {t['purpose']} [{t['audit_status']}]"
            o.append(f'<path class="edge" data-from="{t["from"]}" data-to="{t["to"]}" data-tip="{_esc(tip)}" d="M{x1},{y1 - 4} C{mx},{y1 - 4} {mx},{y2 - 4} {x2},{y2 - 4}" fill="none" stroke="#0F766E" stroke-width="{1.6 if t["audit_status"] == "confirmed" else 1}" stroke-opacity="{0.6 if t["audit_status"] == "confirmed" else 0.35}" stroke-dasharray="{"" if t["audit_status"] == "confirmed" else "4 3"}"{efade(t["from"], t["to"])} style="cursor:pointer"/>')
    for r in L["relationships"]:
        if r["subject"] in pos and r["object"] in pos and r["role"] in ("investor", "principal", "pays", "board", "employee", "observer", "founder", "advisor"):
            a, b = r["subject"], r["object"]
            (x1, y1), (x2, y2) = pos[a], pos[b]
            left = a if x1 <= x2 else b
            if x1 > x2: x1, x2, y1, y2 = x2, x1, y2, y1
            x1 += min(len(nm(left)) * 6, cw - 20); mx = (x1 + x2) / 2
            tip = f"{r['row_id']} {E[a]['name']}: {r['role']} at {E[b]['name']}" + (f", {r['start']}" if r["start"] else "") + (f" to {r['end']}" if r["end"] else "") + f". {r['notes']} [{r['audit_status']}]"
            o.append(f'<path class="edge" data-from="{a}" data-to="{b}" data-tip="{_esc(tip)}" d="M{x1},{y1 - 4} C{mx},{y1 - 4} {mx},{y2 - 4} {x2},{y2 - 4}" fill="none" stroke="#B7791F" stroke-width="1" stroke-opacity="0.45" stroke-dasharray="{"" if r["audit_status"] == "confirmed" else "4 3"}"{efade(a, b)} style="cursor:pointer"/>')
    for e, (x, y) in pos.items():
        dd = d.get(e); k = E[e]["kind"]
        tip = f"{E[e]['name']}: {k}; distance {'unattributed' if dd is None else int(dd)} from a lab. {E[e].get('notes','')}"
        ring = f'<rect x="{x - 4}" y="{y - 13}" width="{min(len(nm(e)) * 6 + 10, cw - 10)}" height="17" fill="none" stroke="{INK}" stroke-width="1.2" rx="3"/>' if e == focus else ""
        o.append(f'<g class="node" data-node="{e}" data-tip="{_esc(tip)}"{nfade(e)} style="cursor:pointer"><rect x="{x - 2}" y="{y - 12}" width="{min(len(nm(e)) * 6 + 6, cw - 14)}" height="15" fill="{PAPER}"/>{ring}<a href="{"../" if focus else ""}entity/{e}.html"><text x="{x}" y="{y}" fill="{"#9B2C2C" if k == "lab" else INK}" font-weight="{"600" if k in ("lab", "evaluator") or e == focus else "400"}">{_esc(nm(e))}</text></a></g>')
    o.append('</svg>')
    return "\n".join(o)
