"""Deterministic SVG figures with data-tip attributes for the site and paper.

path_strips()      Figure 2: the ordered path of each regime (structure, not calendar)
response_plot()    Figure 3: trigger-to-rule lag against instrument strength
mechanism_matrix() Figure 4: who pays, selects, sees, publishes, oversees (now)
"""
from __future__ import annotations
import pathlib
from .paths import paths, analogues, responses, mechanisms, LETTER_LABEL

FONT = 'font-family="Instrument Sans, system-ui, sans-serif"'
INK, MUTED, PAPER, RULE = "#15222E", "#5E6B76", "#F4F6F3", "#D3DAD6"
COL = {"V": "#DCEFEA", "T": "#15222E", "M": "#0F766E", "S": "#8CC5BB", "O": "#2B4C7E", "I": "#6C4AB6", "A": "#3E8E7E", "D": "#B7791F", "P": "#B7791F", "R": "#9B2C2C"}
TXT = {"V": INK, "T": "#fff", "M": "#fff", "S": INK, "O": "#fff", "I": "#fff", "A": "#fff", "D": "#fff", "P": "#fff", "R": "#fff"}

def _esc(s: str) -> str:
    return str(s).replace("&", "&amp;").replace("<", "&lt;").replace('"', "&quot;")

def path_strips() -> str:
    ps = paths(); dist = {a["id"]: a for a in analogues()}
    rh, cell, name_w, pad = 30, 24, 250, 12
    w = name_w + cell * 14 + 300; h = 90 + rh * len(ps) + 40
    o = [f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {w} {h}" width="{w}" height="{h}" {FONT} font-size="12">',
         f'<rect width="{w}" height="{h}" fill="{PAPER}"/>',
         f'<text x="{pad}" y="22" font-size="16" fill="{INK}">Paths: the order each regime did things, ignoring the calendar</text>',
         f'<text x="{pad}" y="40" fill="{MUTED}">Consecutive repeats collapsed. Right column: similarity of each regime\'s opening to frontier AI\'s path so far (1 = identical, 0 = nothing shared).</text>']
    x0 = pad; y = 60
    for n_, (k, lab) in enumerate(LETTER_LABEL.items()):
        if n_ == 6: x0 = pad; y += 18
        o.append(f'<rect x="{x0}" y="{y - 11}" width="14" height="14" rx="2" fill="{COL[k]}"/><text x="{x0 + 18}" y="{y}" fill="{MUTED}">{lab}</text>')
        x0 += 30 + len(lab) * 6.6
    y = 104
    for p in ps:
        ai = p["id"] == "frontier-ai"
        if ai: o.append(f'<rect x="{pad - 4}" y="{y - 2}" width="{w - 2 * pad + 8}" height="{rh}" fill="#EAF4F1" rx="3"/>')
        o.append(f'<text x="{pad}" y="{y + 16}" fill="{INK}" font-weight="{"600" if ai else "400"}">{_esc(p["name"][:38])}</text>')
        # one glyph per collapsed step; tooltip lists every milestone in that run
        runs = []
        for s in p["steps"]:
            if runs and runs[-1][0] == s["letter"]: runs[-1][1].append(s)
            else: runs.append([s["letter"], [s]])
        for j, (letter, steps) in enumerate(runs):
            x = pad + name_w + j * cell
            tip = f"{p['name']}: {LETTER_LABEL[letter]}. " + " | ".join(f"{s['year']} {s['event']}" for s in steps)
            o.append(f'<g data-tip="{_esc(tip)}" style="cursor:pointer"><rect x="{x}" y="{y + 3}" width="{cell - 4}" height="{cell - 4}" rx="3" fill="{COL[letter]}"/>'
                     f'<text x="{x + (cell - 4) / 2}" y="{y + 17}" text-anchor="middle" fill="{TXT[letter]}" font-weight="600">{letter}</text>'
                     f'<text x="{x + (cell - 4) / 2}" y="{y + 27}" text-anchor="middle" fill="{MUTED}" font-size="8">{steps[0]["year"]}</text></g>')
        if not ai:
            d = dist[p["id"]]; xr = pad + name_w + 14 * cell + 10
            o.append(f'<rect x="{xr}" y="{y + 7}" width="{max(2, (1 - d["distance"]) * 120)}" height="12" fill="#0F766E" opacity="0.7"/>'
                     f'<text x="{xr + max(2, (1 - d["distance"]) * 120) + 5}" y="{y + 17}" fill="{MUTED}">similarity {1 - d["distance"]:.2f}, opening {d["matched_opening"]}</text>')
        else:
            o.append(f'<text x="{pad + name_w + 14 * cell + 10}" y="{y + 17}" fill="{MUTED}">reference path: {p["letters"]}</text>')
        y += rh
    o.append(f'<text x="{pad}" y="{h - 12}" fill="{MUTED}">Source: data/industries/. Generated by bench.figures.</text></svg>')
    return "\n".join(o)

def response_plot() -> str:
    rs = responses(); w, h = 760, 380; pl, pr, pt, pb = 60, 20, 60, 50
    xmax = 20; pw, ph = w - pl - pr, h - pt - pb
    o = [f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {w} {h}" width="{w}" height="{h}" {FONT} font-size="12">',
         f'<rect width="{w}" height="{h}" fill="{PAPER}"/>',
         f'<text x="{pl}" y="22" font-size="16" fill="{INK}">After a failure: how fast the next rule came, and how strong it was</text>',
         f'<text x="{pl}" y="40" fill="{MUTED}">Each point is one trigger incident. Hollow points: no rule followed. Frontier AI in teal.</text>']
    for s in range(1, 5):
        yy = pt + ph - (s - 1) / 3 * ph
        o.append(f'<line x1="{pl}" x2="{w - pr}" y1="{yy}" y2="{yy}" stroke="{RULE}"/><text x="{pl - 8}" y="{yy + 4}" text-anchor="end" fill="{MUTED}">{s}</text>')
    for lag in range(0, xmax + 1, 5):
        xx = pl + lag / xmax * pw
        o.append(f'<text x="{xx}" y="{h - pb + 18}" text-anchor="middle" fill="{MUTED}">{lag}</text>')
    o.append(f'<text x="{pl + pw / 2}" y="{h - 12}" text-anchor="middle" fill="{INK}">years from trigger to next rule</text>')
    o.append(f'<text transform="translate(16,{pt + ph / 2}) rotate(-90)" text-anchor="middle" fill="{INK}">instrument strength (1 disclosure to 4 structural)</text>')
    # deterministic jitter by index
    for i, r in enumerate(rs):
        ai = r["regime"] == "frontier-ai"
        if r["lag"] is None:
            xx = pl + pw + 6; yy = pt + ph + 4 - (i % 5) * 6
            tip = f"{r['name']}, {r['year']}: {r['trigger']}. No rule of any kind followed in the dataset."
            o.append(f'<circle data-tip="{_esc(tip)}" cx="{xx}" cy="{yy}" r="6" fill="none" stroke="{"#0F766E" if ai else INK}" stroke-width="1.5" style="cursor:pointer"/>')
            continue
        jit = ((i * 7) % 11 - 5) * 2.2
        xx = pl + min(r["lag"], xmax) / xmax * pw + ((i * 3) % 5 - 2) * 2.4
        yy = pt + ph - (r["strength"] - 1) / 3 * ph + jit
        tip = f"{r['name']}, {r['year']}: {r['trigger']} ({r['harm']}). Response after {r['lag']} year(s), strength {r['strength']}: {r['response_year']} {r['response']}"
        o.append(f'<circle data-tip="{_esc(tip)}" cx="{xx:.1f}" cy="{yy:.1f}" r="{7 if ai else 6}" fill="{"#0F766E" if ai else INK}" fill-opacity="{0.9 if ai else 0.55}" style="cursor:pointer"/>')
    o.append(f'<text x="{pl + pw + 6}" y="{pt + ph + 22}" text-anchor="middle" fill="{MUTED}" font-size="10">none</text>')
    o.append('</svg>')
    return "\n".join(o)

def mechanism_matrix() -> str:
    ms = mechanisms(); cols = [("pays", "Who pays"), ("selects", "Who selects"), ("access", "What they see"), ("publishes", "What the public reads"), ("oversees", "Who watches assessors")]
    val_col = {"A": ("#9B2C2C", "assessed party"), "R": ("#2B4C7E", "regulator or state"), "O": ("#0F766E", "opposing exposure"), "Ph": ("#6C4AB6", "philanthropy"), "self": ("#5E6B76", "self-organized"),
               "shallow": ("#9B2C2C", "shallow"), "deep": ("#8CC5BB", "deep"), "embedded": ("#0F766E", "embedded"),
               "none": ("#9B2C2C", "none"), "summary": ("#8CC5BB", "summary or mark"), "public": ("#0F766E", "public"),
               "self-reg": ("#B7791F", "industry self-regulation"), "regulator": ("#0F766E", "regulator")}
    rh, cw, name_w, pad = 26, 168, 250, 12
    w = pad + name_w + cw * len(cols) + 20; h = 80 + rh * len(ms) + 30
    o = [f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {w} {h}" width="{w}" height="{h}" {FONT} font-size="12">',
         f'<rect width="{w}" height="{h}" fill="{PAPER}"/>',
         f'<text x="{pad}" y="22" font-size="16" fill="{INK}">Mechanisms today: the incentive configuration of each regime</text>',
         f'<text x="{pad}" y="40" fill="{MUTED}">Red marks the configuration that concentrates control in the assessed party. Hover a cell for the state before reform.</text>']
    for j, (_, lab) in enumerate(cols):
        o.append(f'<text x="{pad + name_w + j * cw + cw / 2}" y="66" text-anchor="middle" fill="{INK}" font-weight="600">{lab}</text>')
    ai_now = next(m["now"] for m in ms if m["id"] == "frontier-ai")
    y = 78
    for m in ms:
        ai = m["id"] == "frontier-ai"; same = (m["now"] == ai_now and not ai)
        if ai: o.append(f'<rect x="{pad - 4}" y="{y - 2}" width="{w - 2 * pad + 8}" height="{rh}" fill="#EAF4F1" rx="3"/>')
        o.append(f'<text x="{pad}" y="{y + 16}" fill="{INK}" font-weight="{"600" if ai else "400"}">{_esc(m["name"][:36])}{" (same as AI)" if same else ""}</text>')
        for j, (key, lab) in enumerate(cols):
            v = m["now"][key]; b = m["before"][key]; col, label = val_col[v]
            tip = f"{m['name']}, {lab.lower()}: {label} now; before reform: {val_col[b][1]}. {m['note']}"
            x = pad + name_w + j * cw
            o.append(f'<g data-tip="{_esc(tip)}" style="cursor:pointer"><rect x="{x + 2}" y="{y + 2}" width="{cw - 4}" height="{rh - 6}" rx="2" fill="{col}" fill-opacity="{0.9 if col != "#8CC5BB" else 1}"/>'
                     f'<text x="{x + cw / 2}" y="{y + 16}" text-anchor="middle" fill="{"#fff" if col not in ("#8CC5BB",) else INK}">{label}{"" if v == b else " *"}</text></g>')
        y += rh
    o.append(f'<text x="{pad}" y="{h - 12}" fill="{MUTED}">* changed since the regime\'s origin. Source: data/industries/ mechanisms. Generated by bench.figures.</text></svg>')
    return "\n".join(o)

def write(dist: pathlib.Path, figs: pathlib.Path) -> None:
    for name, fn in [("paths", path_strips), ("responses", response_plot), ("mechanisms", mechanism_matrix)]:
        s = fn(); (dist / f"{name}.svg").write_text(s); (figs / f"{name}.svg").write_text(s)
