name: pages
on:
  push:
    branches: [main]
permissions: {pages: write, id-token: write, contents: read}
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: {name: github-pages}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/upload-pages-artifact@v3
        with: {path: dist}
      - id: deployment
        uses: actions/deploy-pages@v4
